# master-deploy-work.yml
name: main

on:
  push:
    branches:
      - main # main 브랜치에서 push 이벤트가 일어났을 때 실행
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - name: Generate Environment Variables File for Production # Github Repository Secrets를 통해 변수 파일을 생성
        run: echo "NOTION_SECRET_KEY=${{ secrets.NOTION_SECRET_KEY }}" >> .env.production

        env:
          NOTION_SECRET_KEY: ${{ secrets.NOTION_SECRET_KEY }}

      # 실행 속도를 빠르게 하기 위해 설치된 Node 모듈을 캐시하도록 설정합니다.
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: "true"

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_SECRET_KEY }}
        run: |
          echo ${{ secrets.S3_ACCESS_KEY }}
          aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          out s3://kyuniverse
